

CREATE TABLE SENSOR (
    S_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
    SENSOR_NAME CHAR(254) NOT NULL, 
    SENSOR_TYPE CHAR(50) NOT NULL,
    UNIQUE_ID CHAR(254) NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    CONSTRAINT S_ID_PK PRIMARY KEY (S_ID),
    CONSTRAINT UI_UN UNIQUE (UNIQUE_ID)
);

CREATE TABLE SENSOR_DATA (
    SD_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    SENSOR_ID BIGINT NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    IS_ON BOOLEAN NOT NULL,
    IS_REACHABLE BOOLEAN NOT NULL,
    BATTERY_LEVEL SMALLINT,
    CONSTRAINT SD_ID_PK PRIMARY KEY (SD_ID),
    CONSTRAINT SENSOR_ID_FK FOREIGN KEY (SENSOR_ID) REFERENCES SENSOR(S_ID) 
);

CREATE TABLE LIGHT_DATA (
    SD_ID BIGINT NOT NULL, 
    LIGHT_LEVEL INT NOT NULL, 
    IS_DARK BOOLEAN NOT NULL,
    IS_DAYLIGHT BOOLEAN NOT NULL,
    CONSTRAINT LI_SD_ID_FK FOREIGN KEY (SD_ID) REFERENCES SENSOR_DATA(SD_ID)
);

CREATE TABLE PRESENCE_DATA (
    SD_ID BIGINT NOT NULL, 
    PRESENCE BOOLEAN NOT NULL,
    CONSTRAINT PR_SD_ID_FK FOREIGN KEY (SD_ID) REFERENCES SENSOR_DATA(SD_ID)
);

CREATE TABLE TEMP_DATA (
    SD_ID BIGINT NOT NULL, 
    TEMPERATURE DECIMAL(5,2) NOT NULL, 
    CONSTRAINT TE_SD_ID_FK FOREIGN KEY (SD_ID) REFERENCES SENSOR_DATA(SD_ID)
);

CREATE TABLE PING_DATA (
    SD_ID BIGINT NOT NULL, 
    LATENCY SMALLINT NOT NULL, 
    CONSTRAINT PI_SD_ID_FK FOREIGN KEY (SD_ID) REFERENCES SENSOR_DATA(SD_ID)
);